import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { PowerOutline } from 'react-ionicons'

const Home: NextPage = () => {
  return (
    <label htmlFor="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <input type="checkbox" />
      <div className="icon">
        <div className="shadow"></div>
        <div className="iconBox">
          <PowerOutline />
        </div>
      </div>
    </label>
    
  )
}

export default Home
